steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/aegis-analytics-501521/backend-api',
      '-f', 'backend/Dockerfile',
      '.'
    ]
images:
  - 'gcr.io/aegis-analytics-501521/backend-api'
